//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dorm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DormInfo
    {
        public int id { get; set; }
        public Nullable<int> Broom { get; set; }
        public Nullable<int> Mop { get; set; }
        public Nullable<int> Trash { get; set; }
        public Nullable<int> Water { get; set; }
        public Nullable<int> Broom_Max { get; set; }
        public Nullable<int> Mop_Max { get; set; }
        public Nullable<int> Trash_Max { get; set; }
        public Nullable<int> Water_Max { get; set; }
        public string DateTime { get; set; }
    }
}
