//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dorm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitInfo
    {
        public int id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string DateTime { get; set; }
        public Nullable<int> InOut { get; set; }
        public string StudentName { get; set; }
        public string Remarks { get; set; }
    }
}
